# Generated by Django 4.2.10 on 2024-03-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_group_current_members_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproductaccess',
            name='access_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
